// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: slider

#include "ui.h"
int angle_changed = 0;

void slider_changed(lv_event_t * e)
{
	// Your code here
  int angle_val = 0;
  angle_val = lv_slider_get_value(ui_Slider1);
  lv_arc_set_value(ui_Arc1, angle_val);
  angle_changed = 1;
}

void arc_changed(lv_event_t * e)
{
	// Your code here
  int angle_val = 0;
  angle_val = lv_arc_get_value(ui_Arc1);
  lv_slider_set_value(ui_Slider1, angle_val, LV_ANIM_OFF);
  angle_changed = 1;
}
