// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: uart_test

#include "ui.h"
int led_color = 0;

void turn_red(lv_event_t * e)
{
	// Your code here
  led_color = 1;
}

void turn_green(lv_event_t * e)
{
	// Your code here
  led_color = 2;
}

void turn_blue(lv_event_t * e)
{
	// Your code here
  led_color = 3;
}
